# Generated by Django 4.0.4 on 2022-05-11 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Superuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rogno', models.PositiveBigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=254)),
                ('phone', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usrdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rogno', models.PositiveBigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=254)),
                ('phone', models.PositiveBigIntegerField()),
                ('adv_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.superuser')),
            ],
        ),
        migrations.CreateModel(
            name='Leavedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rogno', models.PositiveBigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('status', models.CharField(max_length=255)),
                ('ref_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.usrdata')),
            ],
        ),
    ]
