# Generated by Django 4.0.4 on 2022-05-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_leavedata_reasontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavedata',
            name='enddate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='leavedata',
            name='startdate',
            field=models.DateField(null=True),
        ),
    ]
